version: '2'

services:
  svc-billing:
    image: jmurihub/seicentobilling:2.1.3
    container_name: billing

    environment:
      - APP_STAGE=TEST
      - DB_URL_TEST=jdbc:sqlserver://[SERVER]:1433;database=[DBNAME];encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      - DB_USR_TEST=[DBUSER]
      - DB_PWD_TEST=[DBPASSWORD]
      - tenantid=[Company.com]
      - clientid=[Azure ClientID]
      - clientkey=[Azure Client Key]
    ports:
      - 19080:8080
    networks:
      - docker-network
    restart: unless-stopped

   
networks:
  docker-network:
    driver: bridge
    