apiVersion: v1
kind: Secret
metadata:
  name: {{ template "seicento-chart.fullname" . }}
  labels:
    app: {{ template "seicento-chart.fullname" . }}
    chart: {{ template "seicento-chart.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.tomcatPassword }}
  tomcat-password: {{ default "" .Values.tomcatPassword | b64enc | quote }}
  {{ else }}
  tomcat-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}